### ISSUE TITLE
Compilation Error on Visual Studio C++

### ISSUE THREAD

**Issue by toge** [linksplatform/Hashing#20]
I met compilation error on Visual Studio C++:
```
include\Platform.Hashing.Crc32.h(19,1): fatal  error C1189: #error:
"compiler is not supported"
```

My environment is here.
|  |  |
|-|-|
|Compiler | Visual Studio C++ 19.36 |
| OS | Windows 10 |
| Platform.Hashing | 0.5.4 |

It appears that the `__MSVC__` macro is the cause.
https://github.com/linksplatform/Hashing/blob/cpp_0.5.4/cpp/Platform.Hashing/Platform.Hashing.Crc32.h#L14-L20

I don't think the macro `__MSVC__` is a predefined macro.
https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170

I think the `_MSC_VER` macro would be more appropriate.

**Comment by nassipkali** [comment]
@toge I replaced it to ```_MSC_VER``` in 0.5.5

**Comment by toge** [comment]
@nassipkali 
Thanks a lot!
